# Form implementation generated from reading ui file 'connection_settings_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ConnectionSettingsDialog(object):
    def setupUi(self, ConnectionSettingsDialog):
        ConnectionSettingsDialog.setObjectName("ConnectionSettingsDialog")
        ConnectionSettingsDialog.resize(400, 200)
        self.formLayout = QtWidgets.QFormLayout(ConnectionSettingsDialog)
        self.formLayout.setObjectName("formLayout")
        self.labelHost = QtWidgets.QLabel(parent=ConnectionSettingsDialog)
        self.labelHost.setObjectName("labelHost")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelHost)
        self.ed_host = QtWidgets.QLineEdit(parent=ConnectionSettingsDialog)
        self.ed_host.setObjectName("ed_host")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.ed_host)
        self.labelPort = QtWidgets.QLabel(parent=ConnectionSettingsDialog)
        self.labelPort.setObjectName("labelPort")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelPort)
        self.ed_port = QtWidgets.QLineEdit(parent=ConnectionSettingsDialog)
        self.ed_port.setObjectName("ed_port")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.ed_port)
        self.labelTimeout = QtWidgets.QLabel(parent=ConnectionSettingsDialog)
        self.labelTimeout.setObjectName("labelTimeout")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelTimeout)
        self.ed_timeout = QtWidgets.QLineEdit(parent=ConnectionSettingsDialog)
        self.ed_timeout.setObjectName("ed_timeout")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.ed_timeout)
        self.labelPoll = QtWidgets.QLabel(parent=ConnectionSettingsDialog)
        self.labelPoll.setObjectName("labelPoll")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelPoll)
        self.ed_poll = QtWidgets.QLineEdit(parent=ConnectionSettingsDialog)
        self.ed_poll.setObjectName("ed_poll")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.ed_poll)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=ConnectionSettingsDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.buttonBox)

        self.retranslateUi(ConnectionSettingsDialog)
        self.buttonBox.accepted.connect(ConnectionSettingsDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(ConnectionSettingsDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ConnectionSettingsDialog)

    def retranslateUi(self, ConnectionSettingsDialog):
        _translate = QtCore.QCoreApplication.translate
        ConnectionSettingsDialog.setWindowTitle(_translate("ConnectionSettingsDialog", "Параметры соединения"))
        self.labelHost.setText(_translate("ConnectionSettingsDialog", "IP-адрес ПЛК:"))
        self.ed_host.setPlaceholderText(_translate("ConnectionSettingsDialog", "например, 192.168.0.1"))
        self.labelPort.setText(_translate("ConnectionSettingsDialog", "Порт:"))
        self.ed_port.setPlaceholderText(_translate("ConnectionSettingsDialog", "например, 502"))
        self.labelTimeout.setText(_translate("ConnectionSettingsDialog", "Таймаут (с):"))
        self.labelPoll.setText(_translate("ConnectionSettingsDialog", "Период опроса (мс):"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ConnectionSettingsDialog = QtWidgets.QDialog()
    ui = Ui_ConnectionSettingsDialog()
    ui.setupUi(ConnectionSettingsDialog)
    ConnectionSettingsDialog.show()
    sys.exit(app.exec())
