# Form implementation generated from reading ui file 'dlgPID_settings.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgHandRegulatorSettings(object):
    def setupUi(self, dlgHandRegulatorSettings):
        dlgHandRegulatorSettings.setObjectName("dlgHandRegulatorSettings")
        dlgHandRegulatorSettings.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=dlgHandRegulatorSettings)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.groupBox = QtWidgets.QGroupBox(parent=dlgHandRegulatorSettings)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 201, 141))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 28))
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(0, 28))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lineEdit_2)
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(0, 28))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lineEdit_3)
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.label)
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.label_3)
        self.verticalLayout.addLayout(self.formLayout)

        self.retranslateUi(dlgHandRegulatorSettings)
        self.buttonBox.accepted.connect(dlgHandRegulatorSettings.accept) # type: ignore
        self.buttonBox.rejected.connect(dlgHandRegulatorSettings.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(dlgHandRegulatorSettings)

    def retranslateUi(self, dlgHandRegulatorSettings):
        _translate = QtCore.QCoreApplication.translate
        dlgHandRegulatorSettings.setWindowTitle(_translate("dlgHandRegulatorSettings", "Настройки ПИД-регулятора момента"))
        self.groupBox.setTitle(_translate("dlgHandRegulatorSettings", "Настройки ПИД-регулятора"))
        self.label.setText(_translate("dlgHandRegulatorSettings", "Kp"))
        self.label_2.setText(_translate("dlgHandRegulatorSettings", "Ki"))
        self.label_3.setText(_translate("dlgHandRegulatorSettings", "Kd"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dlgHandRegulatorSettings = QtWidgets.QDialog()
    ui = Ui_dlgHandRegulatorSettings()
    ui.setupUi(dlgHandRegulatorSettings)
    dlgHandRegulatorSettings.show()
    sys.exit(app.exec())
