# Form implementation generated from reading ui file 'general_settings_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_GeneralSettingsDialog(object):
    def setupUi(self, GeneralSettingsDialog):
        GeneralSettingsDialog.setObjectName("GeneralSettingsDialog")
        GeneralSettingsDialog.resize(406, 301)
        self.verticalLayout = QtWidgets.QVBoxLayout(GeneralSettingsDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.settingsLayout = QtWidgets.QVBoxLayout()
        self.settingsLayout.setObjectName("settingsLayout")
        self.widget = QtWidgets.QWidget(parent=GeneralSettingsDialog)
        self.widget.setObjectName("widget")
        self.settingsLayout.addWidget(self.widget)
        self.verticalLayout.addLayout(self.settingsLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=GeneralSettingsDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(GeneralSettingsDialog)
        QtCore.QMetaObject.connectSlotsByName(GeneralSettingsDialog)

    def retranslateUi(self, GeneralSettingsDialog):
        _translate = QtCore.QCoreApplication.translate
        GeneralSettingsDialog.setWindowTitle(_translate("GeneralSettingsDialog", "Общие настройки системы"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GeneralSettingsDialog = QtWidgets.QDialog()
    ui = Ui_GeneralSettingsDialog()
    ui.setupUi(GeneralSettingsDialog)
    GeneralSettingsDialog.show()
    sys.exit(app.exec())
