# Form implementation generated from reading ui file 'src/ui/general_settings_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets


class Ui_GeneralSettingsDialog(object):
    def setupUi(self, GeneralSettingsDialog):
        GeneralSettingsDialog.setObjectName("GeneralSettingsDialog")
        GeneralSettingsDialog.resize(600, 400)
        self.verticalLayout = QtWidgets.QVBoxLayout(GeneralSettingsDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtWidgets.QSplitter(parent=GeneralSettingsDialog)
        self.splitter.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitter.setObjectName("splitter")
        self.categoryList = QtWidgets.QListWidget(parent=self.splitter)
        self.categoryList.setObjectName("categoryList")
        item = QtWidgets.QListWidgetItem()
        self.categoryList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.categoryList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.categoryList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.categoryList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.categoryList.addItem(item)
        self.pagesStack = QtWidgets.QStackedWidget(parent=self.splitter)
        self.pagesStack.setObjectName("pagesStack")
        self.page_system = QtWidgets.QWidget()
        self.page_system.setObjectName("page_system")
        self.pagesStack.addWidget(self.page_system)
        self.page_general = QtWidgets.QWidget()
        self.page_general.setObjectName("page_general")
        self.pagesStack.addWidget(self.page_general)
        self.page_connection = QtWidgets.QWidget()
        self.page_connection.setObjectName("page_connection")
        self.pagesStack.addWidget(self.page_connection)
        self.page_reports = QtWidgets.QWidget()
        self.page_reports.setObjectName("page_reports")
        self.pagesStack.addWidget(self.page_reports)
        self.page_archive = QtWidgets.QWidget()
        self.page_archive.setObjectName("page_archive")
        self.pagesStack.addWidget(self.page_archive)
        self.verticalLayout.addWidget(self.splitter)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=GeneralSettingsDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(GeneralSettingsDialog)
        QtCore.QMetaObject.connectSlotsByName(GeneralSettingsDialog)

    def retranslateUi(self, GeneralSettingsDialog):
        _translate = QtCore.QCoreApplication.translate
        GeneralSettingsDialog.setWindowTitle(_translate("GeneralSettingsDialog", "Общие настройки системы"))
        __sortingEnabled = self.categoryList.isSortingEnabled()
        self.categoryList.setSortingEnabled(False)
        item = self.categoryList.item(0)
        item.setText(_translate("GeneralSettingsDialog", "Система"))
        item = self.categoryList.item(1)
        item.setText(_translate("GeneralSettingsDialog", "Общие настройки"))
        item = self.categoryList.item(2)
        item.setText(_translate("GeneralSettingsDialog", "Соединение"))
        item = self.categoryList.item(3)
        item.setText(_translate("GeneralSettingsDialog", "Отчеты"))
        item = self.categoryList.item(4)
        item.setText(_translate("GeneralSettingsDialog", "Архив"))
        self.categoryList.setSortingEnabled(__sortingEnabled)
