# Form implementation generated from reading ui file 'src/ui/graph_settings_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets


class Ui_GraphSettingsDialog(object):
    def setupUi(self, GraphSettingsDialog):
        GraphSettingsDialog.setObjectName("GraphSettingsDialog")
        GraphSettingsDialog.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(GraphSettingsDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.graphsLayout = QtWidgets.QVBoxLayout()
        self.graphsLayout.setObjectName("graphsLayout")
        self.verticalLayout.addLayout(self.graphsLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=GraphSettingsDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(GraphSettingsDialog)
        QtCore.QMetaObject.connectSlotsByName(GraphSettingsDialog)

    def retranslateUi(self, GraphSettingsDialog):
        _translate = QtCore.QCoreApplication.translate
        GraphSettingsDialog.setWindowTitle(_translate("GraphSettingsDialog", "Настройки графиков"))
